[package]
name = "maudio-sys"
version = "0.1.5"
license = "MIT"
rust-version = "1.70" # required by bindgen 0.72.1
edition = "2021"
build = "build.rs"
links = "miniaudio"
repository = "https://github.com/someotherself/maudio"
description = "Raw miniaudio bindings for the maudio crate"
categories = ["multimedia::audio", "multimedia"]

[features]
default = []
generate-bindings = ["dep:bindgen"]
supplybin = []
vorbis = []

# Disable specific backends
no-wasapi = []
no-dsound = []
no-winmm = []
no-alsa = []
no-pulseaudio = []
no-jack = []
no-coreaudio = []
no-sndio = []
no-audio4 = []
no-oss = []
no-aaudio = []
no-opensl = []
no-webaudio = []

[build-dependencies.bindgen]
version = "0.72.1"
optional = true

[build-dependencies]
cc = "1.2.51"

[dependencies]
