[package]
name = "maudio-tests"
version = "0.1.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
maudio = { path = "../maudio" }
symphonia = { version = "0.6.0", optional = true, features = ["flac"] }
sdl2 = { version = "0.38.0", optional = true, features = ["bundled", "static-link"] }

[features]
symphonia-decoder = ["dep:symphonia"]
sdl2-backend = ["dep:sdl2"]

[[bin]]
name = "symphonia_decoder"
path = "src/custom_symphonia_decoder.rs"
required-features = ["symphonia-decoder"]

[[bin]]
name = "sdl2_backend"
path = "src/custom_backend_sdl2.rs"
required-features = ["sdl2-backend"]

